name: Node.js CI

on: [push]

jobs:
  VRT:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: pnpm install
    - name: Run backstop tests
      run: pnpm run test:backstop