name: Node.js CI

on: [push]

jobs:
  Use-Docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build with custom Dockerfile
      run: |
        docker build --build-arg NODE_VERSION=16 -f ${GITHUB_WORKSPACE}/vrt/DOCKERFILE -t backstop-vrt ${GITHUB_WORKSPACE}
        echo "Docker build complete"

    - name: Run the container and echo "hello world"
      run: |
        docker run backstop-vrt sh -c "echo 'hello world'"